version: "3"
services:
  redis:
    image: redis
    networks: 
      - webnet
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgressql/data
    networks: 
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "3030:5432"
  web:
    image: slashin
    ports:
      - "8081:8081"
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
networks:
  webnet: